apiVersion: v1
kind: Service
metadata:
  name: egovframe-web
  labels:
    app: egovframe-web
    app.kubernetes.io/name: egovframe-web
    app.kubernetes.io/part-of: egovframe-sample
spec:
  type: NodePort
  selector:
    app: egovframe-web
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30000
